#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx

#code to redirect a specific endpoint (eg: riderect /redirect_me to https://tech.climbkilimanjaro.tech)
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _; \n\trewrite ^\/ridirect_me https:\/\/www.tech.climbkilimanjaro.tech permanent;"
sudo sed -i "s/server_name _;$string_for_replacement/" /etc/nginx/sites-enabled/default

#code to riderect error page and add a ridirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 4044 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\www\/html
;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart server
sudo service nginx restart
