#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
#Distribute requests using roundrobin algorithm 
# Make sure that HAProxy can be managed via init script
# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

#edit config file
server_config=\
"
frontend fedy-frontend
	bind *:80
	mode http
	default_backend fredy-backend
backend fredy-backend
	balance roundrobin
	server 164253-web-01 54.160.95.238 check
	server 164253-web-02 34.207.57.98 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | suod tee -a /etc/default/haproxy

sudo service haproxy restart

