#!/usr/bin/env bash
# debugging nginx port 80
# Delete existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/defualt by creating a symbolic link. 
# Flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
