#!/usr/bin/env bash
#Use prgrep to find process IDs of processes whose name contains "bash"
#The script displays PIDs together with the process names of processes whose names contain the the word bash
#Not allowed to use ps

pgrep -l bash
